# -*- coding: utf-8 -*-
"""
Crop/resize/convert the 2026-09-20 photo set (life-community.png,
about-life.png, business-entertainment.png) and the three selected
"こそだてバトン" app screenshots into web-ready WebP assets.

Originals live in brand/photos/ (kept as-is, never overwritten) and are
never re-generated by AI or otherwise altered in content — only cropped/
resized/re-encoded. Outputs go to public/images/photos/ and
public/images/works/kosodate-baton/.

life-community.png has a small watermark-like icon in the top-left
corner (~x:15-95, y:10-90 at native 1672x941 resolution). Every crop
below either starts its x-origin past x=110 or its y-origin past y=100
so the icon is never included in any output.

Requires: pip install pillow (already installed on this machine).
Run: python brand/process_photos.py
"""
import os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SITE_ROOT = os.path.dirname(HERE)
SRC = os.path.join(HERE, "photos")
PHOTOS_OUT = os.path.join(SITE_ROOT, "public", "images", "photos")
WORKS_OUT = os.path.join(SITE_ROOT, "public", "images", "works", "kosodate-baton")


def save_webp(im, path, max_w, quality):
    if im.mode != "RGB":
        im = im.convert("RGB")
    if im.width > max_w:
        ratio = max_w / im.width
        im = im.resize((max_w, round(im.height * ratio)), Image.LANCZOS)
    im.save(path, "WEBP", quality=quality, method=6)
    print(os.path.relpath(path, SITE_ROOT), im.size)


def main():
    os.makedirs(PHOTOS_OUT, exist_ok=True)
    os.makedirs(WORKS_OUT, exist_ok=True)

    # --- About: already 16:9, used as-is (no crop) ---
    im = Image.open(os.path.join(SRC, "about-life.png"))
    save_webp(im, os.path.join(PHOTOS_OUT, "about-16x9.webp"), max_w=1600, quality=80)

    # --- Business / 01 Entertainment: native 3:2, used as-is (no crop) ---
    im = Image.open(os.path.join(SRC, "business-entertainment.png"))
    save_webp(im, os.path.join(PHOTOS_OUT, "entertainment.webp"), max_w=1200, quality=80)

    # --- Business / 03 Life & Community: tight inset crop (right ~67% of
    # frame, full height). x0=550 already clears the watermark. ---
    im = Image.open(os.path.join(SRC, "life-community.png"))
    inset = im.crop((550, 0, im.width, im.height))
    save_webp(inset, os.path.join(PHOTOS_OUT, "life-inset.webp"), max_w=1000, quality=80)

    # --- Philosophy: wide full-bleed banner crop (full width, top strip
    # removed to clear the watermark). Different role/ratio from the
    # Business inset above so the same source photo doesn't repeat. ---
    im = Image.open(os.path.join(SRC, "life-community.png"))
    banner = im.crop((0, 100, im.width, im.height))
    save_webp(banner, os.path.join(PHOTOS_OUT, "life-banner.webp"), max_w=1672, quality=78)

    # --- こそだてバトン screenshots: no crop, no recolor, no content
    # changes at all — just resized + re-encoded as WebP. ---
    screens = [
        ("06-info-card.png", "info-card.webp"),
        ("09-memo.png", "memo.webp"),
        ("10-share.png", "share.webp"),
    ]
    for src_name, out_name in screens:
        im = Image.open(os.path.join(SRC, "kosodate-baton", src_name))
        save_webp(im, os.path.join(WORKS_OUT, out_name), max_w=700, quality=90)

    print("DONE")


if __name__ == "__main__":
    main()
